cmake_minimum_required(VERSION 3.20)
project(flycam_proto CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE Release)
endif()
find_package(gz-sim8 REQUIRED)
find_package(gz-plugin2 REQUIRED COMPONENTS register)
find_package(gz-rendering8 REQUIRED)
find_package(gz-common5 REQUIRED COMPONENTS geospatial)
add_library(FlyCamProto SHARED flycam_proto.cpp)
target_link_libraries(FlyCamProto PRIVATE gz-sim8::gz-sim8 gz-plugin2::register gz-rendering8::gz-rendering8
  gz-common5::geospatial)
target_compile_options(FlyCamProto PRIVATE -Wall -Wextra)
